### ISSUE TITLE
Component goes from uncontrolled to controlled

### ISSUE THREAD

**Issue by addubinski** [balsamiqLeon/jammming#1]
https://github.com/balsamiqLeon/jammming/blob/006e29a3add0fd49ee20f451d04f121cc21ebadd/src/Components/Playlist/Playlist.js#L20

The input element has a defaultValue and value. Since value is controlled by its props this causes an error in the console and should be avoided since it does not conform to React best practices. Instead try deleting defaultValue and put  value={this.props.playlistName || 'New Playlist'}

**Comment by leon-barnard** [comment]
Addressed with https://github.com/balsamiqLeon/jammming/commit/be97ced1104bea398b564c4449e035779f4e5812
